---
title: "Aiming for zero waste at Masters Games"
date: 
description: "Former WHS student Dylan Martin and Hadi Gurton from Sustainable Whanganui with some of the signs that they hope will encourage Masters Games participants to recycle..."
featured-image: 
excerpt: "Former WHS student Dylan Martin and Hadi Gurton from Sustainable Whanganui with some of the signs that they hope will encourage Masters Games participants to recycle."
gallery-image-1: 
gallery-image-2: 
gallery-image-3: 
gallery-image-4: 
gallery-image-5: 
---

<p><span>Former WHS student Dylan Martin and Hadi Gurton from Sustainable Whanganui with some of the signs that they hope will encourage Masters Games participants to recycle. <br />PHOTO: Bevan Conley.</span></p>
<p>Recycling at the 2015 Masters Games meant eight jumbo skip bins of rubbish didn't end up at the landfill.</p>
<p>And the organisation that runs the recycling facilities at the Masters Games hopes to divert even more rubbish from the landfill this year.</p>
<p>This will be the third time Sustainable Whanganui has provided recycling at the Masters Games, which begin on February 4. The group receives funding for recycling at the Masters Games from the Whanganui District Council through the waste minimisation fund.</p>
<p>Hadi Gurton from Sustainable Whanganui said the Masters Games' target was zero waste - meaning absolutely no rubbish at all - and while that target hasn't yet been met, he's hopeful it will this year.</p>
<p>"Before we got involved, nine jumbo skip bins of waste was generated by the Masters Games, and all of that ended up at the landfill. At the last Masters Games there was only one skip bin of rubbish.</p>
<p>"Obviously that is a huge savings for the Masters Games," Mr Gurton said.</p>
<p>Mr Gurton said Sustainable Whanganui provides recycling stations at the main venue and also promotes what's known as precycling.</p>
<p>"Precycling involves, for example, asking food vendors to use compostable packaging."</p>
<p>However, Sustainable Whanganui is not able to provide recycling at events happening outside the main Masters Games venues, such as Wembley Park.</p>
<p>"We're asking the organisers of those events to do their own recycling, and to bring the recycling to the resource recovery centre," Mr Gurton said.</p>
<p>The organisation currently has about 10 volunteers to help with recycling at the Masters Games, and Mr Gurton said about 10 more were needed.</p>
<p>If you can help, please contact the Whanganui Environment Base on (06) 345 6000.</p>
<p class="clear syndicator"><em>By Anne-Marie McDonald</em><br /><em>Wanganui Chronicle 27/1/17</em></p>

<?php /**PATH C:\whs-webiste\cache/193a8e74472d7908c3fd3cd8bae9fba52bf46cbf.blade.md ENDPATH**/ ?>